### ISSUE TITLE
mkall.sh does not complete without errors

### ISSUE THREAD

**Issue by djernst** [GSA/gsa-icam-card-builder#18]
#### Description of Issue: ####
mkall.sh in the certutils directory fails on line 55

#### Details of Issue: ####
The command that fails is;
sh mkcert.sh -b -s $SUBJ -i ICAM_Test_Card_PIV_RSA_2048_Signing_CA_-_gold_gen3 -t icam-piv-ocsp-valid-rsa-2048 -r rsa2048 --cakey piv-rsa-2048 || exit $?
DEST="../cards/ICAM_Card_Objects/ICAM_CA_and_Signer"

It seems that mkcert.sh does not know what an icam-piv-ocsp-valid-rsa-2048 flag is.  
This line was added recently (on 6/13/2018) SHA-1: d97130bfee5ed764f5e3ed18a7a5085f50de9ede)
I tried both the master and cardlib branches

**Comment by djernst** [comment]
In order for the script to complete without error, I commented out the lines that cause the issue discussed in the Details above as well as several other issues.  Several failures occurred when openssl sa … was executed for several certs. Search for the following in the attached modified mkall.sh script

#dje ## Gen3 OCSP valid signer using RSA 2048 (RSA 2048 CA)
#dje # Gen3 Secure Messaging Key Establishment using ECC P-256 (ECC P-384 CA)
#dje ## Gen3 Secure Messaging Key Establishment using ECC P-384 (ECC P-384 CA)
#dje ## OCSP Gen3 valid signer using ECC P-384 (ECC P-384 Signing CA)

I also found an issue when the ## Card 16 section was executed
I needed to change 
"T=Card_Authent_FASCN_mismatch"
to
"T=Card_Authentication_FASCN_mismatch"
in order for the cp -p commands to work.

[mkall.sh.txt](https://github.com/GSA/gsa-icam-card-builder/files/2912530/mkall.sh.txt)

**Comment by bob-fontana** [comment]
The problem with running that script is that it's was last run about a year ago to produce all of certs for all of the cards we have.  After that, I can't really run it, but instead, add the card to the "mkone.sh" script, which is heavily commented out.  It's possible that the same cert in mkone.sh actually works.

I'll look at it and get it fixed.  Could you upload the /tmp/mkall.log file please?

**Comment by djernst** [comment]
Thank you for the explanation and history of using the mkall.sh script and see why you would not run it after generating the certs the first time.

I did a fresh pull from the repo and it still fails at the same spot.  I see that the diff did not change the -t parameter for mkcert.sh call (-t icam-piv-ocsp-valid-rsa-2048).  Was there a change made to mkcert.sh that did not make it in to the repo? I don't see an option for that parameter listed in the mkcert.sh script.

**Comment by bob-fontana** [comment]
I'm on a different box than the Mac OS X  box that I pushed from last night, but I'm looking at this in the mkall.sh in the repo and copied/pasted the affected lines of code.
```
SUBJ=ICAM_Test_Card_PIV_OCSP_Valid_Signer_gen1-2
sh mkcert.sh -b -s $SUBJ -i ICAM_Test_Card_PIV_Signing_CA_-_gold_gen1-2 -t piv-ocsp-valid-gen1-2 -r 2048 --cakey rsa2048 || exit $?
DEST="../cards/ICAM_Card_Objects/ICAM_CA_and_Signer"
cp -p data/$SUBJ.p12 "$DEST"
cp -p data/pem/$SUBJ.crt "$DEST"
...
## Card 16
T=Card_Authentication_FASCN_mismatch
sh mkcert.sh -w -b -s "ICAM_Test_Card_PIV_Dig_Sig_SP_800-73-4_$T" -i ICAM_Test_Card_PIV_Signing_CA_-_gold_gen1-2 -n 16 -t piv-dig-sig || exit $?
sh mkcert.sh -w -b -s "ICAM_Test_Card_PIV_Key_Mgmt_SP_800-73-4_$T" -i ICAM_Test_Card_PIV_Signing_CA_-_gold_gen1-2 -n 16 -t piv-key-mgmt || exit $?
DEST="../cards/ICAM_Card_Objects/16_$T"
cp -p data/ICAM_*_$T.p12 "$DEST"
cp -p data/pem/ICAM_*_$T.crt "$DEST"
renameIn "$DEST" 1 1```

I then cloned the master branch into a trash directory on my PC and successfully built the ICAM_Test_Card_PIV_OCSP_Valid_Signer_gen1-2 cert in Cygwin.

**Comment by djernst** [comment]
ICAM_Test_Card_PIV_OCSP_Valid_Signer_gen1-2 also builds for me.  The problem is building 
ICAM_Test_Card_OCSP_PIV_RSA_2048_Valid_Signer_gen3 (Line 55 of mkall.sh)

**Comment by bob-fontana** [comment]
Okay, thanks.  You should have two files: /tmp/mkall.log and /tmp/mkcert.log.  Can you upload?  This is a hard script to debug without going into the CA databases and resetting everything and running the script in Cygwin, unfortunately, which would take about hour.  If I get the debug logs, I can probably correct it w/o rebuilding everything.

**Comment by bob-fontana** [comment]
I also made that cert within mkall.sh just now by inserting a giant "if [ 0 -eq 1 ]; then" at line 11, and putting an "fi" at line 47.  I then put an "exit" at what would now be line 55.   That produced this:
```
$ sh mkall.sh
/cygdrive/c/users/Bob.Fontana/Desktop/RAF Certs 2/test/gsa-icam-card-builder/certutils/data /cygdrive/c/users/Bob.Fontana/Desktop/RAF Certs 2/test/gsa-icam-card-builder/certutils

**************************** ICAM Test Card PIV RSA Issued Intermediate CVC Signer ******************************

Issuing piv-content-signer-rsa-2048 cert to /C=US/O=U.S. Government/OU=ICAM Test Cards/CN=ICAM Test Card PIV RSA Issued Intermediate CVC Signer.
MAC verified OK
MAC verified OK
Using configuration from /cygdrive/c/users/Bob.Fontana/Desktop/RAF Certs 2/test/gsa-icam-card-builder/certutils/icam-piv-content-signer-rsa-2048.cnf
Check that the request matches the signature
Signature ok
Certificate Details:
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            a0:00:00:00:00:00:00:00:00:65
        Issuer: C=US, O=U.S. Government, OU=ICAM Test Cards, CN=ICAM Test Card PIV RSA 2048 Signing CA
        Validity
            Not Before: Dec  2 00:00:00 2017 GMT
            Not After : Dec 30 23:59:59 2032 GMT
        Subject: C=US, O=U.S. Government, OU=ICAM Test Cards, CN=ICAM Test Card PIV RSA Issued Intermediate CVC Signer
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:c9:13:31:60:19:77:be:6a:e4:39:cc:c7:83:7c:
                    a0:ff:d3:2f:ec:91:fd:2d:0e:47:2c:ea:00:24:80:
                    23:6d:42:29:78:5b:07:38:63:3c:99:28:04:13:dc:
                    a0:9e:ec:3f:c5:27:7b:82:7a:f1:28:c9:4c:a2:7c:
                    6b:b9:e1:58:a6
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Authority Key Identifier:
                keyid:3F:DC:04:DB:5C:26:E9:A7:FA:60:C2:20:59:82:13:0B:0E:4A:EA:45

            X509v3 Subject Key Identifier:
                BE:92:1F:6B:A5:43:11:96:07:BF:83:56:5D:F1:06:88:3C:4C:05:07
            X509v3 Extended Key Usage: critical
                2.16.840.1.101.3.6.7
            X509v3 Key Usage: critical
                Digital Signature
            Authority Information Access:
                CA Issuers - URI:http://http.apl-test.cite.fpki-lab.gov/aia/certsIssuedToICAMTestCardRSA2048SigningCA.p7c
                OCSP - URI:http://ocsp-piv.apl-test.vendor.fpki-lab.gov

            X509v3 CRL Distribution Points:

                Full Name:
                  URI:http://http.apl-test.cite.fpki-lab.gov/crls/ICAMTestCardRSA2048PIVSigningCA.crl

            X509v3 Certificate Policies:
                Policy: 2.16.840.1.101.3.2.1.48.86

Certificate is to be certified until Dec 30 23:59:59 2032 GMT (5054 days)

Write out database with 1 new entries
Data Base Updated

```

**Comment by bob-fontana** [comment]
That particular cert is for vendors to use to issue OCSP responses for certs that they'll someday be able to upload to the actual OCSP responder's database.  As you can see, mkcadata.sh is being groomed for that.

**Comment by djernst** [comment]
Here is the mkcert.log file.  A mkall.log file did not seem to get generated.

[mkcert.log](https://github.com/GSA/gsa-icam-card-builder/files/2915707/mkcert.log)

**Comment by djernst** [comment]
I am running this on Ubuntu 18.04.1 LTS

**Comment by bob-fontana** [comment]
Looking at the mkcert.log file, it's a usage issue, which suggests that the command line is incorrect.  I do think this is something new with the getopt command, but I haven't had a moment to download an fire up an Ubuntu 18 LTS yet.  The reason I say that is that when called with the same parameters as the mkall.sh script uses, the mkcert.sh script works on the other platforms.

**Comment by djernst** [comment]
Looking at line 190 of the mkcert.sh, I don't see how it could work when the mkall.sh script is passing in "-t icam-piv-ocsp-valid-rsa-2048"  Is the "icam-" string supposed to be stripped off somewhere?

**Comment by bob-fontana** [comment]
Yes.  There's a pattern match:

```    -t|--type)
      case "$2" in
        piv-auth*|piv-card-auth*|pivi-auth*|pivi-card-auth*| \
        piv-dig-sig*|piv-key-mgmt*|pivi-dig-sig*|pivi-key-mgmt*| \
        piv-key-hist*|pivi-key-hist*| \
        piv-*-signer*|pivi-*-signer*| \
        piv-ocsp*|pivi-ocsp*) TYPE=$2 ; shift 2 ;;
        *) usage 1 ;;```

You gave me a good clue and I found the culprit.  Thanks.
